### ISSUE TITLE
Peer feedback!

### ISSUE THREAD

**Issue by rebeccargh** [broovygroovy/binding#1]
Hi Bhroovi! This looks great! I love your choice of typefaces especially. One thing I notice is some of the elements are not functioning responsively (the chapters on the landing pages and the menu spacing against the margins) - I like what you've done with switching the flexbox from row to column on the typeface article so this would work great here.

You could also think about increasing the font size on the titles to increase hierarchy differences, although it's already a clear difference right now. 

I really like how you've "bookended" the site with the blue title at the top and the color blocking at the bottom, although the padding between the title of the site and the article could be pushed a little more just to increase this feeling and really cement the top and tail effect.

Can't wait to see how this looks at the end!

**Comment by broovygroovy** [comment]
Thank you so much! i made all the edits you mentioned! See you tommorow! :)
